import { describe, test, expect } from "vitest";
import {
  inferSongInfo,
  normalizeForCmp,
  similarityScore,
  normalizeChannelToArtist,
  extractPrimaryArtist,
} from "./trackInfo";

describe("trackInfo helpers", () => {
  describe("normalizeForCmp", () => {
    test("should lowercase and remove common noise words", () => {
      expect(normalizeForCmp("Binz Official Music")).toBe("binz");
      expect(normalizeForCmp("Vevo Entertainment Production")).toBe("");
      expect(normalizeForCmp("JustaTee Records")).toBe("justatee");
    });

    test("should strip punctuation and extra spaces", () => {
      expect(normalizeForCmp("Hello, World! (Remix)")).toBe("hello world remix");
    });
  });

  describe("similarityScore", () => {
    test("exact match should return 1", () => {
      expect(similarityScore("Binz", "Binz")).toBe(1);
    });

    test("substring match should return 0.8", () => {
      expect(similarityScore("Binz Da Poet", "Binz")).toBe(0.8);
      expect(similarityScore("Binz", "Binz Da Poet")).toBe(0.8);
    });

    test("word overlap >= 50% should return 0.5", () => {
      expect(similarityScore("Binz Da Poet", "Binz Poet")).toBe(0.5);
    });

    test("shorter string (>= 3 chars) in longer string should return 0.8 due to substring check", () => {
      expect(similarityScore("JustaTee", "JustaTeeMusic")).toBe(0.8);
    });

    test("word from shorter string in longer string should return 0.4", () => {
      expect(similarityScore("OnlyC Production", "OnlyC")).toBe(1); // normalized to identical strings because "Production" is noise.
      // Let's test a case where it returns 0.4
      // shorterStr = "abc xyz", longerStr = "def abc ghi"
      // abc length is 3, present in longerStr
      expect(similarityScore("abc xyz", "def abc ghi")).toBe(0.4);
    });
  });

  describe("normalizeChannelToArtist", () => {
    test("should remove - Topic suffix", () => {
      expect(normalizeChannelToArtist("JustaTee - Topic")).toBe("JustaTee");
      expect(normalizeChannelToArtist("Binz - topic")).toBe("Binz");
    });

    test("should remove channel noise", () => {
      expect(normalizeChannelToArtist("Binz Official Music")).toBe("Binz");
    });
  });

  describe("extractPrimaryArtist", () => {
    test("should strip feat / ft", () => {
      expect(extractPrimaryArtist("Binz feat. SOOBIN")).toBe("Binz");
      expect(extractPrimaryArtist("Binz (feat. SOOBIN)")).toBe("Binz");
      expect(extractPrimaryArtist("Binz [ft. SOOBIN]")).toBe("Binz");
    });

    test("should split collaboration separators and return primary", () => {
      expect(extractPrimaryArtist("Binz x SOOBIN")).toBe("Binz");
      expect(extractPrimaryArtist("Binz & SOOBIN")).toBe("Binz");
      expect(extractPrimaryArtist("Binz, SOOBIN")).toBe("Binz");
    });
  });
});

describe("inferSongInfo", () => {
  test("Topic channels (auto-generated by YouTube)", () => {
    const title = "She Neva Knows";
    const channelName = "JustaTee - Topic";
    const description = `Provided to YouTube by Universal Music Group

She Neva Knows · JustaTee

JustaTee The Album

℗ 2012 ...`;

    const result = inferSongInfo(title, channelName, description);
    expect(result).toEqual({
      artistName: "JustaTee",
      trackName: "She Neva Knows",
      albumName: "JustaTee The Album",
    });
  });

  test("Title with trailing pipe and album metadata", () => {
    const title = "07. Em - Binz (feat. SOOBIN) | Gặp Lại Album";
    const channelName = "Binz Da Poet";
    
    const result = inferSongInfo(title, channelName);
    expect(result).toEqual({
      artistName: "Binz",
      trackName: "Em",
      albumName: "Gặp Lại Album",
    });
  });

  test("Title with pipe-separated artist and track", () => {
    const title = "Binz | Em | Gặp Lại Album";
    const channelName = "Binz Da Poet";
    
    const result = inferSongInfo(title, channelName);
    expect(result).toEqual({
      artistName: "Binz",
      trackName: "Em",
      albumName: "Gặp Lại Album",
    });
  });

  test("Title with OST suffix", () => {
    const title = "Love On The Brain | Rihanna | OST";
    const channelName = "Rihanna";

    const result = inferSongInfo(title, channelName);
    expect(result).toEqual({
      artistName: "Rihanna",
      trackName: "Love On The Brain",
      albumName: "OST",
    });
  });

  test("Title with bracketed EP", () => {
    const title = "Binz - Em [Gặp Lại EP]";
    const channelName = "Binz Da Poet";

    const result = inferSongInfo(title, channelName);
    expect(result).toEqual({
      artistName: "Binz",
      trackName: "Em",
      albumName: "Gặp Lại EP",
    });
  });

  test("Description explicit metadata labels (Vietnamese & English)", () => {
    const title = "Binz - Em";
    const channelName = "Binz Da Poet";
    const description = `
Tên album: Gặp Lại
Ca sĩ: Binz
Bài hát: Em
`;
    const result = inferSongInfo(title, channelName, description);
    expect(result).toEqual({
      artistName: "Binz",
      trackName: "Em",
      albumName: "Gặp Lại",
    });
  });

  test("Description performed by metadata", () => {
    const title = "Em";
    const channelName = "Binz Da Poet";
    const description = `
performed by Binz
Album: Gặp Lại
`;
    const result = inferSongInfo(title, channelName, description);
    expect(result).toEqual({
      artistName: "Binz",
      trackName: "Em",
      albumName: "Gặp Lại",
    });
  });

  test("Description with runaway/excessively long metadata line", () => {
    const title = "Binz - Em";
    const channelName = "Binz Da Poet";
    const longArtist = "a".repeat(151);
    const description = `
Artist: ${longArtist}
Album: Gặp Lại
`;
    const result = inferSongInfo(title, channelName, description);
    expect(result.artistName).toBe("Binz");
    expect(result.albumName).toBe("Gặp Lại");
  });

  test("Collaborative title with x / ft", () => {
    const title = "SOOBIN x Binz - BLACKJACK (Official Music Video)";
    const channelName = "SOOBIN";
    
    const result = inferSongInfo(title, channelName);
    expect(result.artistName).toBe("SOOBIN");
    expect(result.trackName).toBe("BLACKJACK");
  });

  test("Reversed dash-separated Title (Track - Artist)", () => {
    const title = "Em - Binz";
    const channelName = "Binz Da Poet";

    const result = inferSongInfo(title, channelName);
    expect(result.artistName).toBe("Binz");
    expect(result.trackName).toBe("Em");
  });

  test("Special dash characters (en-dash and em-dash)", () => {
    const resultEn = inferSongInfo("Binz – Em", "Binz Da Poet");
    expect(resultEn.artistName).toBe("Binz");
    expect(resultEn.trackName).toBe("Em");

    const resultEm = inferSongInfo("Binz — Em", "Binz Da Poet");
    expect(resultEm.artistName).toBe("Binz");
    expect(resultEm.trackName).toBe("Em");
  });

  test("Fallback to channel name when parsing fails", () => {
    const title = "Vlog dạo phố cuối tuần";
    const channelName = "Binz Da Poet";
    
    const result = inferSongInfo(title, channelName);
    expect(result.artistName).toBe("Binz Da Poet");
    expect(result.trackName).toBe("Vlog dạo phố cuối tuần");
  });

  test("Remove noise from title and clean track name", () => {
    const title = "Binz - Em (Official Lyric Video 4K)";
    const channelName = "Binz Da Poet";

    const result = inferSongInfo(title, channelName);
    expect(result.artistName).toBe("Binz");
    expect(result.trackName).toBe("Em");
  });
});
